version: "3.9"

services:
  database:
    image: postgres
    container_name: database
    restart: always
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=hackathon
      - POSTGRES_DB=cardprice
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: cardprice
    restart: always
    ports:
      - 8080:8080
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local